language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install tox-travis
  - pip install -r requirements.txt
  - pip install tox coveralls
script:
  - tox -r
after_success:
  coveralls